language: objective-c
osx_image: xcode10.1
os: osx
sudo: true
cache:
- bundler
- cocoapods
rvm:
- 2.1.0
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - secure: DQUmS7odVwC6uNhkn/bBrvWBvd5xLryd8R2MX51UYv8M8ZMK5b31Ykxgt55UIqYtBgDeouJmtW7aeT40zrS4nUKmJYPZzYnaijfG+qffHKbf85arbpLXz3joUpoFfG3M1p2GYx+tlxGr+dXrz1e3dRFCmk27h42ShdadpZvs1yk=
matrix:
  include:
  - env: NAME='[ObjC] iOS' SCHEME='iOS Tests (ObjC)' DESTINATION='platform=iOS Simulator,name=iPhone
      7 Plus,OS=12.1'
  - env: NAME='[ObjC] macOS' SCHEME='OSX Tests (ObjC)' DESTINATION='platform=macOS'
before_install:
- sudo gem install xcpretty-travis-formatter
- sudo gem install cocoapods --pre
script:
- set -o pipefail
- curl -X 'POST' 'https://api.travis-ci.org/repo/pubnub%2Fjavascript/requests' -H 'Content-Type: application/json' -H 'Accept: application/json' -H 'Travis-API-Version: 3' -H 'Authorization: token ${TEST_TOKEN}' -d $'{"request":{"branch":"CE-3355-Message-Counts-API"}}'
- xcodebuild -workspace ./PubNub.xcworkspace -scheme "${SCHEME}" -destination "${DESTINATION}"
  clean build test | xcpretty -f `xcpretty-travis-formatter`
after_success:
- bash <(curl -s https://codecov.io/bash)
after_failure:
- cat -n ~/Library/Logs/scan/*
- cat -n $TMPDIR/com.apple.dt.XCTest-status/Session*.log
- cat -n ~/Library/Logs/DiagnosticReports/xctest*.crash
